name: IRCTC-Project

on:
  push:
    branchs:
      - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: deploy To Main(PROD)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY}}
        script: |
            cd /home/${{ secrets.USERNAME }}

            # Clone the repository if it doesn't exist
            if [ ! -d "IRCTC_clone" ]; then
              git clone https://github.com/RaNaJitu/IRCTC_clone.git
            fi

            cd IRCTC_clone

            # Pull the latest code
            git pull origin main

            # Build and restart containers
            docker compose up -d --build